### ISSUE TITLE
Linux/Max compatibility: No module named 'winreg'

### ISSUE THREAD

**Issue by nicofilliol** [ClimenteA/flaskwebgui#1]
Is there a way to make this compatible with Mac/Linux? Currently, it throws this error:
```python
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/anaconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda3/lib/python3.7/site-packages/flaskwebgui.py", line 96, in open_browser
    browser_path = self.find_browser()
  File "/anaconda3/lib/python3.7/site-packages/flaskwebgui.py", line 66, in find_browser
    import winreg as reg
ModuleNotFoundError: No module named 'winreg'
```

Since this module isn't available (and required) on Linux/Mac, I suppose flaskwebgui only works on Windows?

**Comment by ClimenteA** [comment]
It works for all, but it finds chrome automatically only in windows for now. I will add a more readable error.

A quick fix is this: `FlaskUI (app, browser_path=r"path/to/chrome.exe")`

My recommended way of using flaskwebgui is this:

- Download portable [Chromium](https://chromium.woolyss.com/) for the targeted os

- place the extracted portable app next to "main.py" file, 

- rename the folder (that contains chrome.exe) "chrome" and when started it will look for  "chrome/chrome.exe" or ""chrome/bin/chrome.exe"

In this way when you distribute it you don't need to other users to have chrome installed, it will work like a portable app.

 Also, during development of your app do that in the normal way you do a Flask app without flaskwebgui. Use flaskwebgui only when you are finished the app and ready to deploy.

flaskwebgui doesn't interfere with your way of doing a flask application it just helps converting it into a desktop app more easily with pyinstaller or [pyvan](https://github.com/ClimenteA/pyvan)

**Comment by ClimenteA** [comment]
Added suport for linux and mac also

**Comment by justinmoon** [comment]
@ClimenteA: If I wanted to use `flaskwebui` to distribute pyinstaller-based binaries for linux users, would I need to have chromium binaries for each distribution? Or is there a single "portable chromium" that would work on all / most distros?

**Comment by ClimenteA** [comment]
> @ClimenteA: If I wanted to use `flaskwebui` to distribute pyinstaller-based binaries for linux users, would I need to have chromium binaries for each distribution? Or is there a single "portable chromium" that would work on all / most distros?
> 
> The website you link above seems to point you in different directions depending on distro ...
