### ISSUE TITLE
Using system default browser to display flask app

### ISSUE THREAD

**Issue by byryepez** [ClimenteA/flaskwebgui#101]
Hello. 

I noticed that depending on the OS, `flaskwebgui` chooses one specific web browser to display the flask app. Especifically in Windows, the default value is to open `msedge.exe`, and only chooses `chrome.exe` when the first is not installed. 

Could be possible to use the default browser chosen in the OS configuration instead of the `flaskguiweb` default browser? I know it is possible to include the `browser_path` but I think using the system default browser is the best. 

Cheers !

**Comment by ClimenteA** [comment]
Hi,

You have `browser_path` if you want to specify another browser of your choosing as you specified. No matter the default browser it will still show the same window so I see no use case here.
