### ISSUE TITLE
Pickle Error on startup

### ISSUE THREAD

**Issue by MarlinSchaefer** [ClimenteA/flaskwebgui#103]
Hey, thanks for publishing this code.

I ran into the following error when trying the example:
```AttributeError: Can't pickle local object 'Flask.__init__.<locals>.<lambda>'```

I'm using Python 3.10 on macOS 12. It seems that the issue is the startup method from the multiprocessing module.
To solve this issue, I added
```mp.set_start_method('fork')```
before calling `FlaskUI` inside the `if __name__ == "__main__"` clause. That seems to be working, but I'm not sure it is a permanent fix, given that it is labeled unsafe in the documentation [https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods).

**Comment by ClimenteA** [comment]
Every working solution can be a permanent solution imo :))

I don't have a mac so it's hard for me to test this. On ubuntu and windows it works. The MacOS VM didn't want to work on my machine...

I will include your fix at least it works, but if you find a better solution in your opinion feel free to make a PR.

**Comment by ClimenteA** [comment]
Released v1.0.2
