### ISSUE TITLE
 How to create an exe ?

### ISSUE THREAD

**Issue by vikramsamak** [ClimenteA/flaskwebgui#104]
How to create an exe of desktop app developed by using flaskwebgui?

**Comment by ClimenteA** [comment]
See pyinstaller, cx_freeze, py2app or pyvan. Try them all and keep what's working out for you.

**Comment by vikramsamak** [comment]
I'm looking for a proper procedure ?

**Comment by AleHS-99** [comment]
pyinstaller create the .exe but do not run the server for flask, whath i'm doing wrong?

**Comment by vikramsamak** [comment]
Try auto py to exe .. while making exe include static and templates folder and choose window application

**Comment by vikramsamak** [comment]
https://pypi.org/project/auto-py-to-exe/

**Comment by AleHS-99** [comment]
i did it but again make the .exe inluce the static and templates folder and run the view but does not run the server

**Comment by AleHS-99** [comment]
ok it works now

**Comment by AleHS-99** [comment]
a directory, now i see the problem, if i open whit the file explorer evrithing go right, but if i doit with TotalCommander do not work then

**Comment by vikramsamak** [comment]
Ohh I see

**Comment by AleHS-99** [comment]
thanks anyway
