### ISSUE TITLE
How to convert TensorFlow bit-lama.ckpt to big-lama.pt

### ISSUE THREAD

**Issue by tomtao008** [ClimenteA/flaskwebgui#108]
hello ,  i have some ckpt file from lama , how can convert ckpt to pt format ?

**Comment by ClimenteA** [comment]
No idea, try chatgpt.

**Comment by Tirbo06** [comment]
`don't mind me... ` 🤓
@tomtao008 
![Screenshot_20230223_144835_Pydroid 3](https://user-images.githubusercontent.com/59821431/220926838-741626a3-e384-4d20-86f3-01a9d6b81f49.jpg)
