### ISSUE TITLE
 flaskwebgui  with ngrok

### ISSUE THREAD

**Issue by cmsethi** [ClimenteA/flaskwebgui#109]
Hi, I tried to run with ngrok/pyngrok, but the GUI window opened only on the localhost url.
Is there anyway to run with Ngrok?
I'm in the learning process.
Thanks

**Comment by ClimenteA** [comment]
Hi, flaskwebgui is to be used for creating desktop apps (rather mimic  them). If you need a web app you don't need flaskwebgui.
