### ISSUE TITLE
Using an ico?

### ISSUE THREAD

**Issue by xpierroz** [ClimenteA/flaskwebgui#119]
Hi, since there's no discussion panel with this repo i'm gonna ask it here.

How can I use an ico with FlaskwebGUI and NiceGUI?

**Comment by ClimenteA** [comment]
See how to add an icon with pyinstaller. In addition add a favicon icon in your index.html file `head`.

**Comment by xpierroz** [comment]
However I don't have a index.html since i'm using NiceGUI and I don't plan compiling it to an .exe, there's no other way?

**Comment by ClimenteA** [comment]
See docs: https://nicegui.io/documentation/html
