### ISSUE TITLE
App closes immediately after start in new version (0.1.7)

### ISSUE THREAD

**Issue by alicjamusial** [ClimenteA/flaskwebgui#12]
If any Chrome window is already opened - app closes immediately after start. The browser window with front-end remains opened, but python script finishes abruptly :(.

If there are no Chrome windows opened - everything works as it should.

I tried your example code from `materialize_theme` folder, but unfortunately the behaviour is the same. 

OS: Windows 7, Chrome v. 79.0.3945.130

**Comment by ClimenteA** [comment]
Hi,
I deleted 0.1.7 (on ubuntu doesn't do that).

It's hard to find if flaskwebgui window was closed if other chrome instances are opened...
