### ISSUE TITLE
How to change timeout of waitress (deadline)? (By default it is 300.0Seconds)

### ISSUE THREAD

**Issue by vikramsamak** [ClimenteA/flaskwebgui#120]
I want to change timeout of waitress how can I do that ?

**Comment by ClimenteA** [comment]
Upgrade to newest version. There the need for timeout was removed.

**Comment by vikramsamak** [comment]
*I updated flaskwebgui to 1.0.4*
I want to change that because it takes 5 minutes to generate a connection error. As I am using Firebase (database) in my project, I have to handle connection errors.

**Comment by ClimenteA** [comment]
I don't get it. If the connection error is related to Firebase that should be handled in the application code.
