### ISSUE TITLE
Is it possible to open 2 instances of flaskwebgui?

### ISSUE THREAD

**Issue by GianniRusso86** [ClimenteA/flaskwebgui#121]
With the old version 0.3.7 I was able to open 2 instances of flaskwebgui

        def run_gui_thread():
            ui = FlaskUI(self.server, maximized=True, idle_interval=28800)
            ui.run()

        run_thread = Thread(target=run_gui_thread, name="run new gui")
        self._config()
        run_thread.start()

With the new version how can I have 2 instances of flaskwebgui? If yes, how do I do it?

Thanks in advance

**Comment by ClimenteA** [comment]
Try with the newer version. Reopen if it doesn't work.
