### ISSUE TITLE
close_application method does not work in fastapi example

### ISSUE THREAD

**Issue by Ppang0405** [ClimenteA/flaskwebgui#125]
```
from flaskwebgui import FlaskUI, close_application
```
when I call `close_application`. the desktop app does not close. works fine in Flask desktop app but not Fastapi desktop app.

<img width="700" src="https://github.com/ClimenteA/flaskwebgui/assets/33455900/88097bb3-ce18-4192-ac5e-0a180e4c9d95" />

**Comment by ClimenteA** [comment]
Thank you for opening this issue. Indeed the fastapi example didn't work. 

I updated the examples folder all should be good now.
