### ISSUE TITLE
Bump up Chrome for Windows users

### ISSUE THREAD

**Issue by cyberz3r0** [ClimenteA/flaskwebgui#128]
For Mac and Linux, chrome application path is listed first in the find_browser_on_{os_name} functions but it's the third option for windows. This by defaults to Edge if installed on a x86 and x64 system. For the sake of consistency, is it possible to bump the chrome application path as the first path checked for windows?
![image](https://github.com/ClimenteA/flaskwebgui/assets/79277456/7fed61c7-6c75-4412-9b0c-0e7a91b53720)

**Comment by ClimenteA** [comment]
I doesn't matter which one is picked up the same blank window is available (Edge is available by default in windows). 

If you want, you can specify `browser_path` in `FlaskUI` class.
