### ISSUE TITLE
Is Flask a dependency?

### ISSUE THREAD

**Issue by riziles** [ClimenteA/flaskwebgui#132]
I love this tool. Quick question for you: when I install with Conda or Mamba, it wants to install Flask as a dependency.

Is Flask actually a dependency if I'm using FastAPI? I went through your code, and it doesn't seem like I need Flask.

**Comment by ClimenteA** [comment]
Thank you!

True, it has only psutil as a dependency.

I don't maintain the conda version that was done by another contributor (maybe it got out of sync).

The pypi one is up to date and it's the one I maintain. 

Try to use the one on pypi with pip or copy the source code in your project.
