### ISSUE TITLE
Prevent users from opening multiple apps at the same time

### ISSUE THREAD

**Issue by Sunyang12345678** [ClimenteA/flaskwebgui#136]
![image](https://github.com/ClimenteA/flaskwebgui/assets/20241273/c41f4cef-6ae7-4bcf-bf88-dc87d6971603)
In flaskwebgui, is there any command support that prohibits users from opening multiple applications at the same time? After opening the application, when the user clicks again, a dialog box will pop up to tell the user that the current application is already open.

**Comment by ClimenteA** [comment]
Some value saved in temp folder indicating that the app is opened/closed could be added to add this option. Feel free to make a PR for this issue and the other one you opened (I don't have much time at the moment).

**Comment by ClimenteA** [comment]
Checking if flaskwebgui has a port open may indeed be a better solution. Maybe I can set process name for flaskwebgui on startup to make that work.

**Comment by ClimenteA** [comment]
Did a little bit of digging and I saw that the second/third etc instances of the app didn't worked. Only first instance of the app worked. I separated the profile browser data for each app instance run so now all open instances will work.

Unfortunately, allowing only one window open is not possible without causing side effects.

Ex: If pc/laptop is shutdown we don't have control over the state of the app (open, closed). It will be considered in open state and if only one instance is allowed - app will not open. Having fixed ports on flaskwebgui is tricky you may have running processes on that port.
