### ISSUE TITLE
Missing Firefox and Chromium

### ISSUE THREAD

**Issue by williamjmorenor** [ClimenteA/flaskwebgui#139]
Hello, and first than all Thank You!

I have a personal project in which having the option to offer the application as a desktop application is an important option for me (yes, not everyone knows how to manage a server, for those people double click on an icon and interact with the application locally is enough even if the data is not backed up to the cloud automatically). I was exploring creating a web browser with PyQT and similarly starting a server as a sub process, seeing the proposed code that starts a server as a sub process, and then lets the user's already installed web browser display the UI to the user It is much simpler than what I was working on, plus it allows the browser to interact with subsystems such as printing that are more complicated from the PyQT side.

Obviously most of those people are Windows users, and MS Edge is the first option that is validated and is supposed to always be available.

But in the list of browsers I think Firefox and Chromium should be available.

Another point is that on Linux many people are using Flatpacks or Snaps to install applications, so searching in "urs/bin" might not always return a browser.

It seems like an easy change, I can work on a proposal in my free time.

**Comment by ClimenteA** [comment]
I'm glad you found it useful! 

Indeed, browser binary may be on a different location depending of package manager used to install the browser.

More possible paths to would be useful to have. 

Firefox will not work, only browsers built on top of chromium.

A PR will be welcomed if you want to contribute.

Otherwise, I'll keep this issue open until I get some time to work on it.

**Comment by ClimenteA** [comment]
I added chromium to the list of browser paths. On linux if those paths will not be found `which` command will be used to find chrome binary path no matter which package was used to install the browser.

```shell
subprocess.check_output(["which", os.path.basename(path)])
```

Plus the developer using flaskwebgui if it has a special case can provide it's own browser_path. 

Ex: `FlaskUI(browser_path=custom_func_finding_browser_path())`
