### ISSUE TITLE
change launch url

### ISSUE THREAD

**Issue by pawrequest** [ClimenteA/flaskwebgui#140]
is it possible to change the initially loaded url?

my flaskwebgui script takes cli inputs, fetches data, and adds to a sqlmodel db, getting an id number at the same time.

i want the application to launch at localhost/{id_number}

so i need to pass it in somewhere? server_kwargs maybe?

sorry if this isnt the place to ask...  

does it become the right place to ask if i also mention pypi projectpage links aren't working?

**Comment by pawrequest** [comment]
url_suffix added in #142

**Comment by ClimenteA** [comment]
You could use the redirect feature of the web framework you are using.
