### ISSUE TITLE
Block browser pop-ups

### ISSUE THREAD

**Issue by fealthaus** [ClimenteA/flaskwebgui#147]
Hey,
Is there any chance to block browser pop-ups? 
For example: Every time I start my ui, the edge browser pops up and asks me if I want to synchronize my microsoft profile. 

Thanks for your support.

**Comment by ClimenteA** [comment]
I just tried to see if I get any popups - for me it didn't show any popups and unfortunately, I can't reproduce to provide some fix.

Look at the source code an see how the browser command is created - try to tweak it from there.

**Comment by nerhZ** [comment]
I've also been having this annoying issue with Edge on every boot where it prompts you to sync your profile. However, I've managed to find a fix: Add the `--guest` flag to your FlaskUI function call as an argument like so `extra_flags="--guest"`. 

At the top of your window it will now say - [Guest], which is slightly annoying but it's the only solution I've found so far. Hope it helps.

**Comment by fealthaus** [comment]
The same works with --inprivate, then it displays " - [InPrivate]". Guest seems a bit better. 
Anyway, thanks for the input from both of you.

**Comment by ClimenteA** [comment]
I think this flag `--disable-sync` should block those pop-ups:

https://peter.sh/experiments/chromium-command-line-switches/
