### ISSUE TITLE
Django auth session loosing when close app

### ISSUE THREAD

**Issue by alnuaimi94** [ClimenteA/flaskwebgui#148]
Hi,
I'm using Flaskwebgui with Django project.

when I closed the app and open it again i lost my authentication session and i have to login again.

**Comment by ClimenteA** [comment]
Checkout how browser_command is built and tweak it. By default browsers starts "fresh" each time. 

For you probably this will do:

```
etc

deskui = FlaskUI(etc)

deskui.profile_dir = os.path.join(tempfile.gettempdir(), "flaskwebgui-custom-app-data") # here it can be any other folder

deskui.run()

```
