### ISSUE TITLE
Inquiry on Update-Support Features in Packaging Tools (CX_FREEZE, PyInstaller, PyVan)

### ISSUE THREAD

**Issue by Kennarttechl** [ClimenteA/flaskwebgui#151]
Dear ClimenteA,

I hope this message finds you well. Thank you for your previous response regarding the Menu Bar feature. Your guidance on using HTML/CSS/JS to create a navbar was very helpful.

I am writing to seek your advice on a different matter. After developing my desktop applications using Flask and Flask-WebGUI, I typically use CX_FREEZE to convert them into executable GUI applications. However, updating these applications after conversion has proven challenging. When my clients request new features, I have to modify the raw code and reconvert the entire application.

I am exploring options to simplify this process and would like to know if any of the following packages—CX_FREEZE, PyInstaller, or PyVan—support behind-the-scenes updates. Specifically, I am looking for a solution where updates can be applied to the application without needing to reconvert it entirely from the raw code each time a new feature is added.

Your expertise and recommendations on this matter would be greatly appreciated.

Thank you for your continued support and for your invaluable contributions to the open-source community.

Best regards,

Kenneth Lumor

**Comment by ClimenteA** [comment]
Hi,

No need to be that formal Kenneth. Let ChatGPT help you on the code. Concise and polite works best in any situation.

An app update feature could be done using the following steps:

1. Make your packaged app available for download via a link (
    - If it's open source you can upload it on github releases;
    - If not, try to look for a solution to download it from an url with a password (a simple flask api on a vps);

2. On app startup make a get request to that flask api to see if a newer version is available;
    - In the ui you can show a notification to inform the user that a newer version is available for download;
    - If the user clicks "Update" button - step 3 should happen;

3. After user clicks update, you make a get request with ApiKey in header to the server holding the newer packaged version (check ApiKey with what you have on the server in .env) ;
    - The packaged zip app will be downloaded next to the main executable (name-of-your-app-v1.2.1.zip);
    - Show a notification to the user to restart app (like you probably saw on vscode when that app updates);
    
4. And from here I don't know what should happen. It's kinda difficult...
    - On app startup check if version from name-of-your-app-v1.2.1.zip is different from what you have in version.txt file next to your executable that starts the app;
    - If it's different then delete current executable and unzip name-of-your-app-v1.2.1.zip (after unzip delete the zip file);

It's pretty difficult to do.. I'm not sure myself how to do it. Hope this helps you a bit.

Good luck!

**Comment by Kennarttechl** [comment]
Ok My Mentor, Thank you and God bless you with more knowledge
