### ISSUE TITLE
My solution to solve the problem that server keeps running after browser window is closed

### ISSUE THREAD

**Issue by ChrisNi888** [ClimenteA/flaskwebgui#152]
The offical document (https://github.com/ClimenteA/flaskwebgui) provide a way to close application:

> Close application using a route
> 
> You can close the application using the close_application function from flaskwebgui.
> from flaskwebgui import FlaskUI, close_application
> 
> 
> @app.route("/close", methods=["GET"])
> def close_window():
>     close_application()
> 
> And somewhere a link:
> <a href="/close" class="exit" role="button">
>     CLOSE
> </a>

This means that by sending a request to the Flask server with the path '/close', the path operation function will call the close_application function to close the background process.

However, this approach requires creating a link, and the user can only close the application by clicking on this link. Users may likely click on the close button in the top right corner of the application (the system's close button, such as the × in Windows), which will not trigger this close request.

How to solve this?

If it's an HTML page, you can add the following script code:

```
<script>
    window.onbeforeunload = async function () {
        try {
            await fetch('/close');
            console.log('Window closed');
        } catch (error) {
            console.error('Error sending request:', error);
        }
    };
</script>
```

If the frontend is built with Vue, you can add the following code in the App.vue file:

```
<script setup lang="ts">
import { onBeforeUnmount, onMounted } from 'vue';
const handleBeforeUnload = async () => {
  console.log('handleBeforeUnload')
  try {
    await fetch('/close');
    console.log('Window closed');
  } catch (error) {
    console.error('Error sending request:', error);
  }
}

onMounted(() => {
  console.log('onMounted')
  // Add the window.onbeforeunload event listener
  window.addEventListener('beforeunload', handleBeforeUnload);
})

onBeforeUnmount(() => {
  console.log('onBeforeUnmounted')
  // Remove the window.onbeforeunload event listener
  window.removeEventListener('beforeunload', handleBeforeUnload);
})
</script>
```

Of course, the specific situation may vary for different projects, and the above code may not be fully applicable, but it can serve as a reference for a solution.

**Comment by ClimenteA** [comment]
> Users may likely click on the close button in the top right corner of the application (the system's close button, such as the × in Windows), which will not trigger this close request.

The close request from link is optional (in case you want to add a close button in your app). Closing from X window will have the same result (closing the server). 

Behind the scenes there is a global variable `FLASKWEBGUI_BROWSER_PROCESS` which keeps track of the browser state (open/closed).

It's safe to close with either of those methods (x window or link close request).
