### ISSUE TITLE
Temp File Accumulation (window)

### ISSUE THREAD

**Issue by pawrequest** [ClimenteA/flaskwebgui#153]
i just found around 500 top-level FlaskWebGui dirs, with 300k files, in 200k subdirs, in C:\Users\USER\AppData\Local\Temp

it was 30GB of flaskwebgui tempfiles

i cleared the temp folder a week ago - i think flaskwebgui is dumping a new load of files with every runtime, and is not cleaning up after itself at all - this 30GB is from the last week only.

i dont really know what normal behaviour would be with temp file management, but until i noticed it had increased system boot times by ~ 1000%.

**Comment by pawrequest** [comment]
addressed in PR #154

**Comment by ClimenteA** [comment]
Nice man! Good catch. 

I thought the OS does some cleaning on the temp folder from time to time.

**Comment by ClimenteA** [comment]
realeased 1.1.3 version with your fix

**Comment by pawrequest** [comment]
Nice one, happy to have contributed!
