### ISSUE TITLE
Web-socket messages bunched together at the end of process    

### ISSUE THREAD

**Issue by catagras** [ClimenteA/flaskwebgui#155]
Hey,

I have this small desktop app that runs a long process in the background and from that process sends status updates to the front end via async websocket.send_text(). The framework used is FastAPI. 

If the server is uvicorn and I connect to the localhost:port from the browser, the WebSocket messages are received when they are emitted.

If I launch the app with FlaskUI only the first message is delivered when emitted, all other messages are delivered at the end of the process microsecconds apart. 

Is it something that I am missing or is it a shortcoming of the flaskwebgui?

<br>

The simplified form of the app will be something like this:

```python

class status:
   def __init__(self) -> None:    
       self._socket: WebSocket

   async def connect(socket: WebSocket) -> None:
        self._socket = socket
        await self._socket.accept()
        await self._socket.receive_text() 

    async def status_update(self, message: str) -> None:
         await self._socket.send_text(message)

status = Status()

async def run_process(status_updates: Callable) -> None:
    await status_update("First Message")
    run_a_process_step()
    await status_update("Second Message")
    # more steps and statuses here
    run_final_step()
    await status_update("Last Message")


app = FastAPI()

@app.post("/actions")
async def run_actions():
    await run_process(status.status_updates)

@app.websocket("/status")
async def status_ws(websocket: WebSocket):
   await status.connect(websocket)

if __name__ == "__main__":
   gui = FlaskUI(server="fastapi", port=8000, app=app)
   gui.run()
```

**Comment by ClimenteA** [comment]
Hi,

Interesting, not sure if is something flaskwebgui related. Flaskwebgui under the hood is pretty basic it just starts a new process/thread for the browser and server.

Try to isolate the issue - run fastapi without flaskwebgui and see if the issue appears. If yes it is a flaskwebgui issue.

**Comment by catagras** [comment]
Indeed it is not related to flaskwebgui.

The symptoms also happen with vanilla uvicorn as soon as I remove the reload=true arg.

I'll dig further on uvicorn for this issue.
