### ISSUE TITLE
Create a flaskwebgui.js file which checks if GUI is opened 

### ISSUE THREAD

**Issue by ClimenteA** [ClimenteA/flaskwebgui#16]
Right now the way flaskwebgui detects if the GUI is opened is hackish..

A default view in flask/django (hidden somewhere on flaskwebgui.py) linked to a flaskwebgui.js with a setTimeout function which from time to time sends a request to inform the server that GUI is still opened will work better that what we have now.

**Comment by alicjamusial** [comment]
Good idea! But maybe sockets will be nicer?

**Comment by ClimenteA** [comment]
I haven't worked with sockets, the ideal is to make flaskwebgui as little to no setup required for it to work.

**Comment by ClimenteA** [comment]
And done. Added a built in get feature from python using http.server.
