### ISSUE TITLE
After closing the window, It still show GUI still open

### ISSUE THREAD

**Issue by vishal2612200** [ClimenteA/flaskwebgui#19]
When I closed the app also, Then also it shows GUI still open. Sometimes it also overtakes the Ctrl+C command in terminal also. This problem occurs in examples/metro4-theme.
Operating System: Ubuntu 18.04 LTS
![flaskwebui](https://user-images.githubusercontent.com/37480057/77782153-d5983880-707c-11ea-8271-6c2b2b5efb48.png)

**Comment by ClimenteA** [comment]
Hi, I'm also on ubungu 18.04 I can't reproduce the error.
Can you add a link to your github repo? (To try reproduce the error on my side)

**Comment by vishal2612200** [comment]
I was using the same code of master branch, without any changes. During the testing of this project, This thing happened on my local computer.

**Comment by ClimenteA** [comment]
Check if you have Chrome installed. I see you added the js code.
