### ISSUE TITLE
When GUI/Browser is closed flask server doesn't stop

### ISSUE THREAD

**Issue by ClimenteA** [ClimenteA/flaskwebgui#2]
there is an issue with the flask_thread doesn't close when gui is closed. Tried to set daemon=True on flask_thread, tried to create another thread which checks if browser is opened but still it doesn't work...

**Comment by Zickfor** [comment]
Greetings.
Maybe you should use PID to check if browser is closed?

**Comment by ClimenteA** [comment]
Hi,
Maybe, I don't know. I didn't had time to work on it.
You can make a pull request/fork and see if you can fix it. 
I will merge your code here (if when I close chrome, flask-server process it's closing too)

**Comment by kdmukai** [comment]
I'm experiencing the same thing. Python 3.7, macOS Catalina. Have to CTRL-C twice to kill the server. The Chrome window is totally independent.

**Comment by ClimenteA** [comment]
I made a little hack, but this will kill all python processes when chrome is closed..
Save this source file where you need it  [flaskwebgui.py](https://raw.githubusercontent.com/ClimenteA/flaskwebgui/master/src/flaskwebgui.py)

For some reason setting the daemon has no effect..

**Comment by polko14** [comment]
There is still an inssue if other chrome instance is opened, i.e. if you're using chrome and flaskwebgui app at the same time you are not able to stop the app's server until you close everything in normal chrome.

**Comment by ClimenteA** [comment]
psutil is used to check if chrome is opened, but it doesn't identify the chrome app instance of flaskwebgui it looks for all chrome instances.

Unfortunately setting a daemon either on server or browser doesn't have any effect.

A fix would be to get the PID when opening chrome (line 180 def open_browser) and close the server when that PID is no longer running (line 208 def browser_runs).

 I will take a look and see what I can do.

**Comment by ClimenteA** [comment]
fixed

**Comment by ddd354** [comment]
I think the new version makes it worse on MacOS Catalina 10.15.1, python 3.7.5, pyenv setup, other chrome windows open. Now when chrome app window opens it shuts down the flask process.

```python run.py                 
 * Serving Flask app "test.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Dec/2019 21:15:42] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Dec/2019 21:15:43] "xxx HTTP/1.1" 200 -
zsh: killed     python run.py```

Reverse to 0.1.2 makes it won't kill the process but closing the app chrome window won't kill the flask process correctly.

**Comment by ClimenteA** [comment]
In ubuntu/windows works. I will try to find a macos iso and see what happend.

Can you show a link to a repo where that failed?

**Comment by ClimenteA** [comment]
Added a quick temorary hack..
```
chrome_pids = [p.info['pid'] for p in psutil.process_iter(attrs=['pid', 'name']) if 'chrome' in p.info['name']]
[psutil.Process(pid).kill() for pid in chrome_pids]
```
This will close all chrome instances when starting flaskwebgui.

Chrome when is opened has more than one chrome process, can't identify all the additional chrome instances when opening chrome with subprocess.

I will need to add some delta to check all chrome instances running before starting flaskwebgui and after then close only the ones after, but still this has an issue with the chrome instances opened after opening flaskwebgui..

**Comment by ClimenteA** [comment]
Subprocess creates a zombie chrome process if chrome was already opened.
That prevents closing server when flaskwebgui chrome instance is closed..
