### ISSUE TITLE
Instance with host="0.0.0.0", app open an invalid url

### ISSUE THREAD

**Issue by youcefmei** [ClimenteA/flaskwebgui#20]
When i create an instance with host="0.0.0.0" ,the browser open with this url.
In this case it should be "127.0.0.1" .

**Comment by ClimenteA** [comment]
Hi, 

Parameter host="0.0.0.0" is to make the app available to other users in the same network. 
flaskwebgui is used to simulate a website as a desktop application. 
If you let it 127.0.0.1 or localhost there should be no problem. 

Thanks for pointing this out, host parameter is rather static than dynamic, change only port parameter is 5000 is used by other applications.
