### ISSUE TITLE
I am not able to change the window size..

### ISSUE THREAD

**Issue by AzadKshitij** [ClimenteA/flaskwebgui#23]
from Project import app
from flaskwebgui import FlaskUI  

ui = FlaskUI(app, width=1200, height=1200, fullscreen=False, maximized=False, app_mode=True,  browser_path="", server="flask", host="127.0.0.1", port=5000, socketio=None, on_exit=None)

if __name__ == "__main__":
    ui.run()

But still screen size is not changing !!

Please Help!!👍👍👍

**Comment by ClimenteA** [comment]
It seems `--window-size` flag is ignored. 
Found an [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=178104) which says that  `--window-size` is sometimes ignored in favor of os last saved data. 

Checkout the src folder from this repo and see if you can solve the issue.

**Comment by ClimenteA** [comment]
Released a new version(0.1.15+), hopefully it fixes this issue.
