### ISSUE TITLE
GUI was closed

### ISSUE THREAD

**Issue by NgoziOkereke** [ClimenteA/flaskwebgui#24]
I am using flaskwebgui, and the main process I run on my application takes at least 20 minutes to complete. This now becomes an issue because after that process is run, the gui closes, stopping the user from using the other features. I know this happens because of this code, https://github.com/ClimenteA/flaskwebgui/blob/80c47e02fe1ffc77e339d36071d14218a08d86e6/src/flaskwebgui.py#L206.
I will like to know how to ensure the gui stays open to allow the user perform other processes.

**Comment by ClimenteA** [comment]
It doesn't work as expected.. It should make a request every 10 sec from the frontend regardless if the user is idle..

Download the source file and comment out the code from line 200 to bellow. 

If you find a solution please make a pull request.

**Comment by NgoziOkereke** [comment]
This issue stopped happening, I did not change anything in the code. So, I am yet to know what caused it, if it starts again, I will reopen the issue. Thanks.
