### ISSUE TITLE
Generated URLS don't open.

### ISSUE THREAD

**Issue by Pneuro** [ClimenteA/flaskwebgui#25]
The follow returns data from a CSV to HTML table, but the URLS that are generated when clicked don't do anything. Looking for a quick fix, the new tab, and new window options aren't functional?

"""
return render_template('result.html', tables=[df.to_html(classes='dataframe', index=False, render_links=True, sparsify=True)], titles=df.columns.values, query=query, download_link=download_link)"""

**Comment by ClimenteA** [comment]
Yes, new tab/window is not suported in app mode. 
Try to set `app_mode=False`, it will open a normal Chrome browser
