### ISSUE TITLE
If multiple copies of a flaskwebgui-derived app are opened from one location, they prevent earlier instances exiting.

### ISSUE THREAD

**Issue by joncage** [ClimenteA/flaskwebgui#28]
Spotted in my project here (using v0.1.9) : https://github.com/joncage/ed-scout/blob/master/EDScoutWebUI/EDScout.py

You use `bo.txt` which is created in the local directory.

A simple fix is to use a temp file as follows:

```
import tempfile
temp_dir = tempfile.TemporaryDirectory()
keepalive_file = os.path.join(temp_dir.name, 'bo.txt')
```

..then refer to keepalive_file elsewhere in the script.

**Comment by ClimenteA** [comment]
Awesome ! thank you :+1:
