### ISSUE TITLE
Can I integrate an Angular project?  

### ISSUE THREAD

**Issue by alymohamedhassan** [ClimenteA/flaskwebgui#35]
I tried to integrate an angular project but, the service failed

**Comment by ClimenteA** [comment]
You must use the compiled js files from Angular. The production files.
If you are using flaskwebgui from `ng serve` will not work, must be from `python yourfile.py`.

**Comment by alymohamedhassan** [comment]
I did that but the app simply returned an Internal server error and couldn't know why because the service kept working in the background and I couldn't stop it.

I will close the issue until I fix the other problem
