### ISSUE TITLE
Not able to open when using development environment

### ISSUE THREAD

**Issue by jpick713** [ClimenteA/flaskwebgui#36]
I was driving myself mad since I kept getting this error no matter how I tried to have the app (application factory pattern, multiple files, one huge main.py file with all models, routes, forms et al in one file! et al). I kept getting this error
ValueError: signal only works in main thread

I finally started just removing stuff one at a time from .env and .flaskenv files and voila, when I removed the development environment variable, it worked!

My question, though, is there a way to run this in debug mode? Was it just some other mistake I made, or is this related to that old SocketIO bug with development environments perhaps?

Anyways, 
Great idea and since I have made lots of Flask Web apps, this was much easier for me than PySimpleGUI that I was trying to use for some of my clients who wanted desktop GUIS (and looks a lot better!). I hope to dive into this package more as I make more GUIs.

Thanks,
Jamie Pickett

**Comment by ClimenteA** [comment]
Anything that works in a Flask app should work with no problem with flaskwebgui. Some issues may occur if you have threading/async functionalities somewhere in your code (but python is good with us and shows a nice traceback of the error).

Debug mode would mean to develop the application as usual in Flask (`without ui.run(), just app.run()`).

```py

from flask import Flask
from flaskwebgui import FlaskUI 

DEBUG = True

app = Flask(__name__)
ui = FlaskUI(app)

@app.route("/")
def index():
  return "It works!"


if DEBUG:
  # call the 'run' method
  ui.run()
else:
  app.run()

```

I'm glad it helps :)  
I used it to create some 'desktop applications' at the company I worked for. I found tkinter and other alternatives to be bit more complicated than they should've been.
