### ISSUE TITLE
flask server not in GUI

### ISSUE THREAD

**Issue by jasruf** [ClimenteA/flaskwebgui#39]
Hi, i am trying to run the flaskwebgui both for the user on the same device, as for external users. when i set the host to "0.0.0.0" i can reach the webserver from the network, but i can't set the flaskwebgui screen to the addres "127.0.0.1".
if i set the host to 127.0.0.1 the server is unreachable for other devices. How can i achieve both the GUI as the server working simultaneously?

**Comment by ClimenteA** [comment]
Flaskwebgui is for a desktop application setup. 

If you want to serve multiple users from the same setup then [deploy it on a server](https://flask.palletsprojects.com/en/1.1.x/deploying/).

**Comment by jasruf** [comment]
Thank you for the quick reply!
