### ISSUE TITLE
Replacing flask server with wsgi server(waitress)

### ISSUE THREAD

**Issue by baietoo** [ClimenteA/flaskwebgui#41]
I have been using the library succesfully for local apps(thank you for sharing!) and I have a small curiosity:
Could one be able to serve the app instead of simply using ui.run() with the flask server?

Been tinkering but I've not been able to run it:
```
ui = FlaskUI(serve(app), port=8080)
```

I know it was not made for multiple users only for local but do you have any ideas that might point me in the right direction.

the app is hosted on a shared Drive from where multiple users are accessing it reading and writing data to a sqlite db.

Thank you again for this awesome library!

**Comment by ClimenteA** [comment]
Checkout server parameter. On server param you can add a function which starts the server.

**Comment by ClimenteA** [comment]
Also checkout pyvan,

**Comment by baietoo** [comment]
It worked! added WSGIServer to the run_flask function, http://www.gevent.org/api/gevent.pywsgi.html
