### ISSUE TITLE
GUI Returning "This site can't be reached"

### ISSUE THREAD

**Issue by AnshKetchum** [ClimenteA/flaskwebgui#45]
Before the update, my GUI would open a flask window. 
Every time I run my GUI now (Flask Application), I receive this error:

```
This site can’t be reached 127.0.0.1 refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSE
```

Also, do we still need the js script in ``base.html`` or can I remove that?

**Comment by ClimenteA** [comment]
no need for js script

**Comment by AnshKetchum** [comment]
Hi ClimenteA, 
Thank you for taking time to help me. I removed the js script. I keep getting the message above and I am not sure why. When I use the old code, it at least opens the GUI.

I use the following code to start the app and ``FlaskUI``

```
app = Flask(__name__, static_folder= os.path.join(RESOURCES_FOLDER, 'static'), template_folder= os.path.join(RESOURCES_FOLDER, 'templates'))

def run_desktop():
    open_preferences()
    ui = FlaskUI(app,on_exit=save_preferences, port=5000)
    ui.run()
```

**Comment by ClimenteA** [comment]
The js is cached by browser, clear cache from chrome settings and try again, it should work.

**Comment by AnshKetchum** [comment]
Hi ClimenteA, 

I cleared the cache and I am still receiving the same error.

**Comment by ClimenteA** [comment]
Can you give me access to your repo? I will try to reproduce it on my side. Also check if http://localhost:5000 works in normal browser.

**Comment by AnshKetchum** [comment]
I checked if  [ http://localhost:5000](http://localhost:5000), and it doesn't; I get the same error. As for the code, I tested a basic flask application with 1 index route, and I also get the same error.

**Comment by ClimenteA** [comment]
I can't figure out what's going on.. can you give me access to your repo? Or try to provide a full example when this error occurs?

**Comment by AnshKetchum** [comment]
Sure, I'll give you access to my repository. Can I make you a private collaborator for now? I don't want the repository to be public.

**Comment by ClimenteA** [comment]
It's ok private.

**Comment by ClimenteA** [comment]
If port is already in use then it can't open the server so you get `Site can't be reached` error.

**Comment by AnshKetchum** [comment]
I checked all ports using ``sudo lsof -t -i tcp:``, none had any other process running. When I re-ran the same code, I still get the same error.

**Comment by ClimenteA** [comment]
I made an update to fix the open port issue, reinstall flaskwebgui and it will work, hopefully :))
