### ISSUE TITLE
After close GUI on_exit doesn't call my function

### ISSUE THREAD

**Issue by Imanthee** [ClimenteA/flaskwebgui#46]
In **examples** it doesn't call this function.

```python

def bread(): return print('Close')

if __name__ == '__main__':
	FlaskUI(app, start_server='flask-socketio', socketio = socketio, on_exit=bread).run()

```

```md

Server initialized for threading.
WARNING:root:Detected webframework flask-socketio
1htiioPjdMT6tZAAAAAA: Sending packet OPEN data {'sid': '1htiioPjdMT6tZAAAAAA', 'upgrades': [], 'pingTimeout': 5000, 'pingInterval': 25000}
INFO:engineio.server:1htiioPjdMT6tZAAAAAA: Sending packet OPEN data {'sid': '1htiioPjdMT6tZAAAAAA', 'upgrades': [], 'pingTimeout': 5000, 'pingInterval': 25000}
1htiioPjdMT6tZAAAAAA: Received packet MESSAGE data 0
INFO:engineio.server:1htiioPjdMT6tZAAAAAA: Received packet MESSAGE data 0
1htiioPjdMT6tZAAAAAA: Sending packet MESSAGE data 0{"sid":"ELiszscI8-D8qe1FAAAB"}
INFO:engineio.server:1htiioPjdMT6tZAAAAAA: Sending packet MESSAGE data 0{"sid":"ELiszscI8-D8qe1FAAAB"}
1htiioPjdMT6tZAAAAAA: Received packet CLOSE data 
INFO:engineio.server:1htiioPjdMT6tZAAAAAA: Received packet CLOSE data

```

**Comment by ClimenteA** [comment]
After you close the gui you should see this message in logs: "closing connections..." (In max 5 sec)

Not sure why this is not showing in your logs. 

Does Flask-socketio example work for you?

**Comment by ClimenteA** [comment]
```py
import logging

def bread():
    logging.warning("close")

...
```

Try up instead, you can't do anything with the return from on_exit func

**Comment by Imanthee** [comment]
I haven't got any explicit data in my logs: 'closing connections...'

'flask-socketio' and default 'flask' working same for me. I hope so.

I tested function with logging and no change.

**Comment by FilipKod** [comment]
@ClimenteA  I also tried using `on_exit` and I found problem with psutils.Process which stop loop before if statement. 

https://github.com/ClimenteA/flaskwebgui/blob/master/src/flaskwebgui.py#L259

But unfortunatly I can not recognize why this happening. When I tried remove line 259 and also remove `pid_memory_usage == 0` from statement, then it worked correctly or better 😄.

**Comment by ClimenteA** [comment]
Yeah, detecting if gui is closed doesn't seem to work consistently.

For me either pid_running worked either pid_memory_usage worked that's why I added an or condition there.

**Comment by FilipKod** [comment]
I understand and I also see OR condition. In my case after closing app pid_exists() is called and work properly but psutil.Process() behaves as if it try to create instance, pause a program and still try it without success. So while loop behaves as if it pause and wait for instance create but that will not happen, never. 

I hope u understand me. 😄

**Comment by ClimenteA** [comment]
It hangs on `pid_memory_usage = psutil.Process(self.BROWSER_PROCESS.pid).memory_percent()`? 

Can you give me a full example to test it on my side?

**Comment by ClimenteA** [comment]
Made an update to use `is_running` insead of `pid_exists`, probablly will work for you too.
