### ISSUE TITLE
Error: "127.0.0.1 refused to connect."

### ISSUE THREAD

**Issue by AnshKetchum** [ClimenteA/flaskwebgui#47]
When I run my program, I get a window with this error message:

```
This site can’t be reached 127.0.0.1 refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
```

Note 1: I am not sure if this is related, but I first ran my code using ``python3 app.py``. I got this error, which forced me to unnecessarily use sudo afterwards. Now, I have to use ``sudo`` everytime, which is weird since the action in question is only opening a ``shelf``. 
```
 File "app.py", line 334, in run_desktop
    open_preferences()
  File "app.py", line 294, in open_preferences
    my_shelf = shelve.open(fp)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dbm/__init__.py", line 94, in open
    return mod.open(file, flag, mode)
_dbm.error: [Errno 13] Permission denied
```

Note 2: I am only using the ``flaskwebgui.py`` file liked the README.md suggests, I didn't use ``pip install`` to download the package and then import it.

**Comment by ClimenteA** [comment]
That's not related to flaskwebgui..

**Comment by AnshKetchum** [comment]
I am aware that the error isn't related to it. I resolved that issue using ``sudo``, but I thought it may help you to know that it occurred. But my gui still doesn't load and I get the "127.0.0.1 refused to connect" error, which I believe is due to ``flaskwebgui``.

**Comment by ClimenteA** [comment]
Are you using the `0.2.1` version?

**Comment by AnshKetchum** [comment]
I am not sure what version I am using, but I am using the source code from ``flaskwebgui.py`` that is in the repository.

**Comment by FilipKod** [comment]
@ClimenteA  hi bro did you know that `memory_percent()` return float and not integer?

This:
```python
gui_memory_usage = int(psutil.Process(self.BROWSER_PROCESS.pid).memory_percent())
```
should be:
```python
gui_memory_usage = float(psutil.Process(self.BROWSER_PROCESS.pid).memory_percent())
```
if talk about version `0.2.1`.

**Comment by ClimenteA** [comment]
`0 == 0.0`

**Comment by FilipKod** [comment]
But `int(0.65)` still return as `0` (zero).

**Comment by ClimenteA** [comment]
yep, you are right, I will remove `int` casting

**Comment by ClimenteA** [comment]
added the update even though the probability of a chrome window to use less than 1mb is very slim :)

**Comment by ClimenteA** [comment]
@AnshKetchum not much I can do without testing your code on my side too.

**Comment by AnshKetchum** [comment]
@ClimenteA , I gave you a private invitation to the repository with my code. Please download it and test it from your side.

**Comment by ClimenteA** [comment]
I don't see any private repo showing in my list..

Does your program work without flaskwebgui?

**Comment by AnshKetchum** [comment]
I sent you an invitation; GitHub has sent you an email to be a colaborator for a repository called 'LightSpeed'. 

My program also runs in the web perfectly well without ``flaskwebgui``.

**Comment by ClimenteA** [comment]
I double checked email and repos, nothing related to LightSpeed showing up..

If it works well without flaskwebgui then it must be something related to multiple ports used idk.

**Comment by AnshKetchum** [comment]
Alright, I made it public. It is the only repository pinned on my profile page. Can you take a look and see if you can view it now?

**Comment by ClimenteA** [comment]
- Clean your os (do a fresh install if posible)  
- START using virtual environments, 
- STOP using globals.. 
- your app worked for me with no issues 
 
![image](https://user-images.githubusercontent.com/9250009/112269390-fcce1980-8c80-11eb-860c-3915b5e116d6.png)
![image](https://user-images.githubusercontent.com/9250009/112269675-5afafc80-8c81-11eb-8521-9aef3006f7ed.png)

**Comment by AnshKetchum** [comment]
I just cleaned my ``os``. 

But now, I am getting the following error: 
```
(env) AnshKetchum:LightSpeedSrc foo$ python3 app.py
Traceback (most recent call last):
  File "/Users/foo/Desktop/LightSpeedSrc/env/lib/python3.7/site-packages/psutil/_psosx.py", line 344, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/foo/Desktop/LightSpeedSrc/env/lib/python3.7/site-packages/psutil/_psosx.py", line 534, in connections
    rawlist = cext.proc_connections(self.pid, families, types)
PermissionError: [Errno 1] Operation not permitted (originated from proc_pidinfo())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 342, in <module>
    run_desktop()
  File "app.py", line 337, in run_desktop
    ui.run()
  File "/Users/foo/Desktop/LightSpeedSrc/env/lib/python3.7/site-packages/flaskwebgui.py", line 101, in run
    self.update_port_if_used()
  File "/Users/foo/Desktop/LightSpeedSrc/env/lib/python3.7/site-packages/flaskwebgui.py", line 272, in update_port_if_used
    connections = psutil.net_connections()
  File "/Users/foo/Desktop/LightSpeedSrc/env/lib/python3.7/site-packages/psutil/__init__.py", line 2153, in net_connections
    return _psplatform.net_connections(kind)
  File "/Users/foo/Desktop/LightSpeedSrc/env/lib/python3.7/site-packages/psutil/_psosx.py", line 249, in net_connections
    cons = Process(pid).connections(kind)
  File "/Users/foo/Desktop/LightSpeedSrc/env/lib/python3.7/site-packages/psutil/_psosx.py", line 351, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=1060)

```

If I bypass using ``sudo``, the window doesn't even open. It simply terminates.

**Comment by ClimenteA** [comment]
Try something else, pywebgui, eel, flask-desktop maybe those will work for you

**Comment by AnshKetchum** [comment]
I ended up fixed the problem by using ``pip install flaskwebgui`` instead of copying the src code. But the issue now is that the thread still remains open even after I close the GUI. I have to manually close it using CTR+C every time.

**Comment by ClimenteA** [comment]
Uninstall then reinstall chrome. Clean everything related to chrome. Maybe it will work.

Anyway thanks for opening the issue I ended up making flaskwebgui better by removing the js dependency.
