### ISSUE TITLE
Start_server parameter

### ISSUE THREAD

**Issue by wanderer799** [ClimenteA/flaskwebgui#49]
Hi,
When I try to run the demo code i am getting this exception 
"Exception: Please fill start_server parameter with one of the following values: flask-socketio, flask, django, fastapi", where should i fill this parameter?

**Comment by ClimenteA** [comment]
Demo code should work for all but if it fails do this:

```py
FlaskUI(app, start_server="flask")
```

**Comment by wanderer799** [comment]
Thanks
