### ISSUE TITLE
Flask missing as dependency

### ISSUE THREAD

**Issue by zauberparacelsus** [ClimenteA/flaskwebgui#5]
I tried this out real quick after seeing the medium article on it, and ran across a problem.  When installed via pip, it does not appear to install Flask if you don't already have it installed, so when I ran the example script, I got an error about flask not being present, and had to run pip again to install it.

Aside from that, it worked like a charm.  Will definitely be making use of this!

**Comment by ClimenteA** [comment]
Added flask as a depedency. 
Plus added Django support also, now you can pass 'django' in server param and make desktop apps in Django also. 
 `FlaskUI(server='django').run()`
