### ISSUE TITLE
Consider fallback to Edge on Windows

### ISSUE THREAD

**Issue by melund** [ClimenteA/flaskwebgui#54]
Could you consider using Microsoft Edge as a fallback on Windows if Chrome is not found?

Thanks for the great work, and a useful package :)

**Comment by ClimenteA** [comment]
Since Edge is now based on Chromium it would be nice indeed to have on windows a default to Edge.

Add Edge .exe path to `browser_path` parameter, it should work.

**Comment by ClimenteA** [comment]
Version 0.3.0 starts by default ms edge.

**Comment by melund** [comment]
Thanks @ClimenteA . Btw. I have added a 'feedstock' conda-forge, so it automatically creates conda packages when you make new PyPI releases.

https://github.com/conda-forge/flaskwebgui-feedstock/issues

So for conda users it can be installed with:

```
conda install -c conda-forge flaskwebgui
```
