### ISSUE TITLE
Server keeps running after browser window is closed

### ISSUE THREAD

**Issue by FFSSolutions** [ClimenteA/flaskwebgui#58]
Using Flask and all runs just fine but when the browser app window closes the server is never killed off. I do see where there is a staticmethod is place trying to monitor the browser pid but doesnt seem to be working.

Is there a way to query from the FlaskUI instance the pid of the browser and I can just do it myself or how do you advise?

**Comment by FFSSolutions** [comment]
Found the issue line 312 and line 313 is throwing exceptions when the browser process is not found and bails out before the cleanup happens, simple fix though.
` while True:
            try:
                gui_running = psutil.Process(self.BROWSER_PROCESS.pid).is_running()
                gui_memory_usage = psutil.Process(self.BROWSER_PROCESS.pid).memory_percent()
            
                if not gui_running or gui_memory_usage == 0:
                    break

                time.sleep(5)
            except Exception as e:
                logging.info('Forced Shutdown Browser Closed')
                break
         
            
        if isfunction(self.on_exit): 
            logging.info(f"Executing {self.on_exit.__name__} function...")
            self.on_exit()
        else:
            logging.info("No 'on_exit' function provided.")

        logging.info("Closing connections...")
        FlaskUI.kill_pids_by_ports(self.port)
        `

**Comment by lpwm** [comment]
I'm facing the same issue! I found there is a parameter named `on_exit` in the `FlaskUI`'s constructor, the docstring described: 
> on_exit                           ==> specify on-exit function which will be run before closing the app

By leaving this `on_exit`  with default value None, the flask won't stop after closing Chrome which is opened by flaskwebgui. I tried to define a function and pass it to `on_exit` like this:

```py
# main.py
from flask import Flask, render_template
from flaskwebgui import FlaskUI


def exit_func():
    print('Exiting....')


app = Flask(__name__)
ui = FlaskUI(app, width=800, height=600, on_exit=exit_func)


@app.route('/')
def index():
    return render_template('index.html')


if __name__ == '__main__':
    ui.run()

```
Nothing changes, and the `exit_func` wasn't triggered either when I force the `main.py` stop.

**Comment by lpwm** [comment]
@FFSSolutions I tried your solution, modify the `flaskwebgui.py` from line 313, wrap a `try except`  then it works! And the `exit_func` works too! The flask will be terminated after 5 seconds after closing Chrome, due to the code `time.sleep(5)`, that's not a issue. Many thanks to you!

Hope the author fix this bug in the future. @ClimenteA 
I do love this wheel! Combining all the advantages with `eel` and `pywebview`, and makes using Python to develop desktop application easier! Thanks to @ClimenteA !

**Comment by ClimenteA** [comment]
Not sure if adding a try except over `gui_running` check will cause the browser closing prematurely see this issue: https://github.com/ClimenteA/flaskwebgui/issues/51

Module psutil seems to work inconsistently, it's hard to get PID of browser especially if there are more chrome windows opened.

**Comment by lpwm** [comment]
> Not sure if adding a try except over `gui_running` check will cause the browser closing prematurely see this issue: #51
> 
> Module psutil seems to work inconsistently, it's hard to get PID of browser especially if there are more chrome windows opened.

I've tried to open two instance of my application, the first one works well with flask working on port 5000, but the second one could only work for seconds, then won't find the right flask server with port 5001, there's only one process from windows' task manager, so I wonder the second process was killed by the `try except` code.

**Comment by ClimenteA** [comment]
The correct PID of the browser is listed in the task manager of the browser (you can find it somewhere on chrome settings/tools).

The while loop checks if browser is_running, without it the server is closed.

To fix this issue we need some sort of listener on the chrome window. If user clicks X then close the server (if you find a way to do this feel free to make a pull request :). Or, some sort of websocket listener which will close the server if connection is ended or lost.


Previously on version 0.0.7, there was some pooling (js code) that send a is alive http request. That version caused for some people other issues (cors or something else, don't remember what was the second issue).

**Comment by tamajon** [comment]
> Found the issue line 312 and line 313 is throwing exceptions when the browser process is not found and bails out before the cleanup happens, simple fix though. just wrapped with try/except and break on exception. Thanks for this handy tool, cheers mate
> 
> ```
> while True:
>             try:
>                 gui_running = psutil.Process(self.BROWSER_PROCESS.pid).is_running()
>                 gui_memory_usage = psutil.Process(self.BROWSER_PROCESS.pid).memory_percent()
>             
>                 if not gui_running or gui_memory_usage == 0:
>                     break
> 
>                 time.sleep(5)
>             except Exception as e:
>                 logging.info('Forced Shutdown Browser Closed')
>                 break
>          
>             
>         if isfunction(self.on_exit): 
>             logging.info(f"Executing {self.on_exit.__name__} function...")
>             self.on_exit()
>         else:
>             logging.info("No 'on_exit' function provided.")
> 
>         logging.info("Closing connections...")
>         FlaskUI.kill_pids_by_ports(self.port)
> ```

This works for me, Thanks you!

**Comment by ClimenteA** [comment]
Version 0.3.0 should fix this issue.

**Comment by vikramsamak** [comment]
> Found the issue line 312 and line 313 is throwing exceptions when the browser process is not found and bails out before the cleanup happens, simple fix though. just wrapped with try/except and break on exception. Thanks for this handy tool, cheers mate
> 
> ```
> while True:
>             try:
>                 gui_running = psutil.Process(self.BROWSER_PROCESS.pid).is_running()
>                 gui_memory_usage = psutil.Process(self.BROWSER_PROCESS.pid).memory_percent()
>             
>                 if not gui_running or gui_memory_usage == 0:
>                     break
> 
>                 time.sleep(5)
>             except Exception as e:
>                 logging.info('Forced Shutdown Browser Closed')
>                 break
>          
>             
>         if isfunction(self.on_exit): 
>             logging.info(f"Executing {self.on_exit.__name__} function...")
>             self.on_exit()
>         else:
>             logging.info("No 'on_exit' function provided.")
> 
>         logging.info("Closing connections...")
>         FlaskUI.kill_pids_by_ports(self.port)
> ```

What I have to do for using this hack ? I'm using flaskwebgui version 0.3.7

**Comment by ChrisNi888** [comment]
The offical document (https://github.com/ClimenteA/flaskwebgui) provide a way to close application:

> Close application using a route
> 
> You can close the application using the close_application function from flaskwebgui.
> from flaskwebgui import FlaskUI, close_application
> 
> 
> @app.route("/close", methods=["GET"])
> def close_window():
>     close_application()
> 
> And somewhere a link:
> <a href="/close" class="exit" role="button">
>     CLOSE
> </a>


This means that by sending a request to the Flask server with the path '/close', the path operation function will call the close_application function to close the background process.

However, this approach requires creating a link, and the user can only close the application by clicking on this link. Users may likely click on the close button in the top right corner of the application (the system's close button, such as the × in Windows), which will not trigger this close request.

How to solve this?

If it's an HTML page, you can add the following script code:

```
<script>
    window.onbeforeunload = async function () {
        try {
            await fetch('/close');
            console.log('Window closed');
        } catch (error) {
            console.error('Error sending request:', error);
        }
    };
</script>
```


If the frontend is built with Vue, you can add the following code in the App.vue file:

```
<script setup lang="ts">
import { onBeforeUnmount, onMounted } from 'vue';
const handleBeforeUnload = async () => {
  console.log('handleBeforeUnload')
  try {
    await fetch('/close');
    console.log('Window closed');
  } catch (error) {
    console.error('Error sending request:', error);
  }
}

onMounted(() => {
  console.log('onMounted')
  // Add the window.onbeforeunload event listener
  window.addEventListener('beforeunload', handleBeforeUnload);
})

onBeforeUnmount(() => {
  console.log('onBeforeUnmounted')
  // Remove the window.onbeforeunload event listener
  window.removeEventListener('beforeunload', handleBeforeUnload);
})
</script>
```


Of course, the specific situation may vary for different projects, and the above code may not be fully applicable, but it can serve as a reference for a solution.
