### ISSUE TITLE
flaskwebgui + flask-socketio

### ISSUE THREAD

**Issue by rodriguesfas** [ClimenteA/flaskwebgui#6]
Hello Friend! First of all I would like to congratulate you on the beautiful work. Second would like help. Yeah, I wanted to use your flask-socketio project how could I do that? Is it supported? thank you in advance, hug.

**Comment by ClimenteA** [comment]
Glad you like it. It's not that complicated check the source file.

`from flask_socketio import SocketIO

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

if __name__ == '__main__':
    socketio.run(app)`

Make a new func
`
def run_sock():
   socketio.run(app)
`

Then pass that func to server parameter in FlaskUI
`FlaskUI(server=run_sock)`

It should work
