### ISSUE TITLE
App close after 5 seconds automatically

### ISSUE THREAD

**Issue by derekcbr** [ClimenteA/flaskwebgui#63]
from flask_script import Manager

app = Flask(__name__)
manager = Manager(app)
ui = FlaskUI(app, width=500, height=500) 

If manager is used, in gui.py do we still need to write like below?
manager = Manager(app)
FlaskUI(manager, width=600, height=500, start_server='flask').run()
or still the same as before?
FlaskUI(app, width=600, height=500, start_server='flask').run()

**Comment by ClimenteA** [comment]
The first one `manager`.
