### ISSUE TITLE
App closes after five seconds- Django 

### ISSUE THREAD

**Issue by incipientss** [ClimenteA/flaskwebgui#64]
**gui.py** 

from flaskwebgui import FlaskUI
from django_mask.wsgi import application

FlaskUI(application,maximized=True,start_server='django').run()

After generating the exe file on double tap the console gets closed automatically after 5 seconds 
and the browser says no internet connection

The console shows information given below:
flaskwebgui - [INFO] - opening browser at http://127.0.0.1:31606
flaskwebgui - [INFO] - middleware not implemented (yet) for Django
'python3' is not recognized as an internal or external command, operable program or batch file.

**Comment by ClimenteA** [comment]
Install `waitress` package and see if it works.

**Comment by incipientss** [comment]
thanks it works..!!! 
But again I came across one more error which is not able to load coco_names.txt present in model_data folder which I have mentioned in datas list in spec file. Do I separately need to mention each file name in datas list...??

**Comment by ClimenteA** [comment]
Read bellow article about static files in packages:
https://alinclimente.hashnode.dev/python-import-errors-and-package-static-files-resources
