### ISSUE TITLE
Application closing even after using keep alive

### ISSUE THREAD

**Issue by FoxBearBear** [ClimenteA/flaskwebgui#66]
Using Flask, Python and Windows, my application closes after running idle for a while or when the computer enters sleep mode.

**Comment by ClimenteA** [comment]
Added the endpoint that deals with pooling back, somehow flask middleware didn't work for you. Try reinstalling the package and see if it works.

**Comment by FoxBearBear** [comment]
> Added the endpoint that deals with pooling back, somehow flask middleware didn't work for you. Try reinstalling the package and see if it works.

I will do it and report later.

How should the endpoint for the keep alive be set up in flask? Just a generic 404 not found or the server needs to return a certain value?

**Comment by ClimenteA** [comment]
If you look at the source code you will see that what keeps the server alive is a after request middleware. I tried keeping the gui up for a few hours while doing something else but didn't encountered any issue.

Each time a request is made or that endpoint called the timeout for the closing server is reset.

**Comment by FoxBearBear** [comment]
> Each time a request is made or that endpoint called the timeout for the closing server is reset.

I see, but should I see something like 

`10.0.0.184 - - [11/Aug/2021 23:29:20] "GET /projeto/flaskwebgui-keep-server-alive HTTP/1.1" 404 -`  ?

Also, is there a way to keep the server running even if the computer enters sleep mode?

**Comment by hellolex** [comment]
I also encounter this problem. When the window is minimized, the background will close in about four or five minutes. When you do not minimize the window, but operate other programs, close it after about ten minutes.

I hope that when I don't click the close button, the program will always be online.

**Comment by ClimenteA** [comment]
Added a quick fix for this. If you set `close_server_on_exit` to `False` the server won't close anymore.

**Comment by Sanster** [comment]
Found a solution here: https://stackoverflow.com/a/31105348/2002510
