### ISSUE TITLE
 Error reporting using fastapi

### ISSUE THREAD

**Issue by fenglingxian** [ClimenteA/flaskwebgui#68]
Use the examples provided by fastapi，“ValueError: signal only works in main thread“
![image](https://user-images.githubusercontent.com/39217825/134457380-34fb57a6-0450-45b0-a7ad-a16037b3866d.png)

**Comment by ClimenteA** [comment]
Added a quick fix for this. If you set `close_server_on_exit` to `False` the server won't close and signal issue won't appear anymore.

The signal error most probably appeared because of the `Lock()` - `release`/`aquire` functionality in the flaskwebgui.

**Comment by fenglingxian** [comment]
What should I do?

`from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from fastapi import FastAPI
from flaskwebgui import FlaskUI

app = FastAPI()
templates = Jinja2Templates(directory="templates")
@app.get("/", response_class=HTMLResponse)
async def root(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})
@app.get("/home", response_class=HTMLResponse)
async def home(request: Request):
    return templates.TemplateResponse("some_page.html", {"request": request})

if __name__ == "__main__":
    def saybye(): print("on_exit bye")

    FlaskUI(app, start_server='fastapi', on_exit=saybye).run()`

**Comment by fenglingxian** [comment]
> 为此添加了快速修复程序。如果设置为服务器将不会关闭，则信号问题将不再出现。`close_server_on_exit``False`
> 
> 信号错误很可能是由于烧瓶中的 - /功能而出现的。`Lock()``release``aquire`

What should I do?

**Comment by ClimenteA** [comment]
Try this:
```py
FlaskUI(app, start_server='fastapi', on_exit=saybye, close_server_on_exit=False).run()
```

**Comment by fenglingxian** [comment]
error message：
![image](https://user-images.githubusercontent.com/39217825/148486770-db548946-2a02-45b6-839d-6421b5da93a4.png)

**Comment by ClimenteA** [comment]
Upgrade to latest version, it should work.

**Comment by fenglingxian** [comment]
Upgrade to latest version, it not work.

**Comment by ClimenteA** [comment]
Run `pip3 show flaskwebgui` in the terminal you should see version 0.3.5

```bash
Name: flaskwebgui
Version: 0.3.5
etc
```

**Comment by alanting850420** [comment]
Still got failed.

![image](https://user-images.githubusercontent.com/11245316/190955540-c1e160a7-9045-430f-96e4-dec98226cd08.png)
