### ISSUE TITLE
defining the port

### ISSUE THREAD

**Issue by roederstompers** [ClimenteA/flaskwebgui#69]
It is possible to define the port permanently because the application should be accessible remotely.

```
    def set_url(self):
        with socketserver.TCPServer(("localhost", 0), None) as s:
            free_port = s.server_address[1]
        self.host = '127.0.0.1'
        self.port = free_port
        self.localhost = f"http://{self.host}:{self.port}" 
  
```

**Comment by ClimenteA** [comment]
Flaskwebgui is intended to be used when you need a 'desktop app' not a server.

If you need the app accessable for other PCs in the network skip flaskwebgui.
