### ISSUE TITLE
Problem starting django server on windows due to no python3 cmd command.

### ISSUE THREAD

**Issue by polko14** [ClimenteA/flaskwebgui#7]
While trying to start django app on windows it doesn't show any error in cmd, but app doesn't render showing only "no connection error" in browser. It's caused by windows having "python" not "python3" as default command for running python. It's used in "run_flask" function:
```python
elif self.server.lower() == "django":
    os.system("python3 manage.py runserver {}:{}".format(self.host, self.port))
```
Simplest fix would be changing it to:
```python
elif self.server.lower() == "django":
    if "win" in sys.platform:
        os.system("python manage.py runserver {}:{}".format(self.host, self.port))
    else:
        os.system("python3 manage.py runserver {}:{}".format(self.host, self.port))
```
But I'm not sure if it's the best solution.

**Comment by ClimenteA** [comment]
You are right :)
 
Added the fix suggested.

I'm using ubuntu as primary, on older versions of python I remember they had in PATH both python.exe and python3.exe
