### ISSUE TITLE
flaskwebgui doesn't work with Flask-Socketio

### ISSUE THREAD

**Issue by hitnik** [ClimenteA/flaskwebgui#71]
It raises: ValueError: signal only works in main thread of the main interpreter.

To fix it, please  change next line

https://github.com/ClimenteA/flaskwebgui/blob/0e592559aacc9e3d5291ca22f54719bda3ac5dd9/src/flaskwebgui.py#L230

to 

self.socketio.run(self.app, host=self.host, port=self.port, debug=False)

**Comment by ClimenteA** [comment]
Done, thank you!
