### ISSUE TITLE
You're using an unsupported command-line flag: --no-sandbox. This poses stability and security risks.

### ISSUE THREAD

**Issue by donno2048** [ClimenteA/flaskwebgui#74]

**Comment by donno2048** [comment]
Using Edge

**Comment by donno2048** [comment]
Pretty sure Edge uses `"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --profile-directory=Default`

**Comment by donno2048** [comment]
Quite sure Edge uses `-no-sandbox`

**Comment by dardar1129** [comment]
I have Same issue, How to remove it ?

**Comment by 11chri** [comment]
I wrote a fix for this: #76
