### ISSUE TITLE
Deployment in Production Mode

### ISSUE THREAD

**Issue by DenizDogan92** [ClimenteA/flaskwebgui#79]
Hi,

Thanks for this great tool. I am using it with flask and socketio but when I run the code using FlaskUI as follows, it always starts in development mode. 

`ui = FlaskUI(app, socketio=socketio, start_server="flask-socketio", host=config.HOST_IP, port=config.HOST_PORT, width=200, height=200, close_server_on_exit=False)
`

How can I run it on production mode for deployment ?

Thanks 
Best

**Comment by ClimenteA** [comment]
There is no production mode with flaskwebgui. 
This package just makes it easy to have the same code you would have for a website, run in a desktop app + access to local drive.
For production deploy your flask app as you would normally do.
