### ISSUE TITLE
Try to specify browser_path but failed in MacOS

### ISSUE THREAD

**Issue by ddd354** [ClimenteA/flaskwebgui#8]
I think the reason is because that:
`os.path.isfile('Chrome.app')` returns False thus it won't continue. (`os.path.exists('Chrome.app')` returns True)

**Comment by ClimenteA** [comment]
`browser_path` parameter must contain full path to chrome exe (including the exe).
Something like bellow:
`'Users/<username>/Library/Application Support/Google/Chrome/Default/Chrome.app'`
I didn't test it on a mac but you try this command in your terminal to find the path to chrome executable:
`find / -type d -name "*Chrome.app"`
