### ISSUE TITLE
How to use JS Framework like ReactJS

### ISSUE THREAD

**Issue by mrkvn** [ClimenteA/flaskwebgui#81]
I'm a noob developer so this is probably a noob question but, how to use this with JS Framework like React?

I've tried to do the normal wiring of Flask + React. localhost:5000 for Flask and localhost:3000 for React.

Then I've run `npm run build` then transferred the `dist` files to flask's directory (putting the `index.html` inside the `templates` directory and the rest to `static` directory and changing the paths in `index.html` file accordingly).

It actually worked when I run it in the browser using `app.run()` but when I ran it on the desktop using `ui.run()`, the app closes.

**Comment by ClimenteA** [comment]
Did you added this [js script](https://github.com/ClimenteA/flaskwebgui#install)?
If that doesn't work set parameter `close_server_on_exit=False`

**Comment by mrkvn** [comment]
Damn! I forgot to include the script in my `index.html` (the one generated by React). I had the script. Just forgot to include it in the generated `index.html`. Told you I'm a noob. Lol. Thanks.
