### ISSUE TITLE
Uncaught TypeError: setInterval and Uncaught SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by mrkvn** [ClimenteA/flaskwebgui#82]
![image](https://user-images.githubusercontent.com/52745562/190425768-17098bdc-b8d0-4b93-b6ea-9e6053b245dc.png)

The screenshot is from this example: https://github.com/ClimenteA/flaskwebgui/tree/master/examples/flask-desktop

I had these errors in my app and I thought I might be doing something wrong. But then I tried to run the provided example and I'm also getting the errors.

 I don't think it's affecting the app functionally, but still, it's an error.

**Comment by ClimenteA** [comment]
Good catch, just pushed a fix for that.
