### ISSUE TITLE
Questions about chrome app

### ISSUE THREAD

**Issue by mrkvn** [ClimenteA/flaskwebgui#84]
Sorry if this should not be in this but I don't know how to ask questions without opening an issue.

Is there a way to disable normal chrome browser functions in the desktop app. I mean, for example, is there a way to disable opening the chrome devtools in the desktop app? For user experience and maybe security. It's weird to open a desktop app and able to open the devtools. Other things are opening a new tab (CTRL+T), or new window (CTRL+N), or refreshing the page (CTRL+R) or any other normal browser functions that should not be possible in a desktop app.

I'm asking this for production, not for development, of course. Thanks

**Comment by ClimenteA** [comment]
No worries. You could catch those inputs with javascript and ignore them. This could be a starting point for what you want > https://stackoverflow.com/questions/2767126/how-to-detect-that-ctrlr-was-pressed
