### ISSUE TITLE
How-to restart Flask server from packaged .app ?

### ISSUE THREAD

**Issue by scipio-nl** [ClimenteA/flaskwebgui#85]
Hello Alin, first off, thanks for taking the time to develop FlaskWebGUI so far.

I ran into a "catch-22" situation with FlaskWebGUI as follows:

- the main use case for FlaskWebGUI, is to be able to deploy client-side running desktop apps with a Flask/Python backend and an html / css / JS frontend, where the browser serves the role as "UI renderer", by packaging the application into a macOS .app or Windows .exe;

- by default, FlaskWebGUI kills the Flask server process, unless a JS script running in the browser keeps polling some (dummy) server route. But when the computer goes idle, sleep, that polling script stops and the Flask server process is killed.
There's currently no easy way to restart the Flask server from a packaged .app.

- if you keep the Flask server running and close the packaged app, on restart a new Flask server process is started and there's no easy way to kill the old one.

So how to resolve this?

**Comment by scipio-nl** [comment]
UPDATE:

Alin, I don't think, from a software architectural point of view, this is the correct solution, but one way to get around the "Catch-22 situation", is as follows:

-1- remove the dummy JS route polling on the UI side of the app;
-2- spawn FlaskWebGui with the flag

```python
gui = flaskwebgui.FlaskUI(app, close_server_on_exit=False)
```
-3- on the Python side, add in a routine to persistently log (write to disk) the current Flask process ID of the packaged .app/.exe by appending the current process ID to the log file, and add in a Flask route that's polled every once in a while from the app's UI side (JS), to check if the same app has running orphan processes, and kill them.

PS: the core of this problem should not occur to begin with. The proper solution is to properly handle the issue within FlaskWebGui itself, by keeping the Flask server running by default and killing its process once the UI closes (either browser itself or browser tab, or some Flask route that's called from JS). In other words a 3rd option to `close_server_on_exit` (0, 1, 2 instead of True/False)

**Comment by ClimenteA** [comment]
The flag `close_server_on_exit=False` should do the trick in the case the pc goes in idle mode. I tried various methods to make it more reasonable, but unfortunately we can't get the PID of the browser open with `subprocess` because chromium browsers spawn dynamically other PID's...

If you have any ideas on how we can get around this any PR's are welcome. 

I'll leave this issue open until we can provide a reasonable solution.

**Comment by scipio-nl** [comment]
Hi Alin,
one way around this, and I think the correct way even, is to re-write how FlaskWebGui spawns a renderer:
- right now, it uses Chrome/Chromium;
- a better way is to make that an optional flag, and instead default to opening a window utilizing the client device system's native Webview. You could take a look at how PyWebview implements this, and implement something similar to FlaskWebGui

An even better approach, is to look into Tauri (see: [https://tauri.app/](https://tauri.app/) ).
Tauri is built with Rust, and has a feature called "SideCar" (see: [https://tauri.app/v1/guides/building/sidecar](https://tauri.app/v1/guides/building/sidecar))where you can include a Python binary, which could be a packaged FlaskWebGui app. This way, you gain (via Tauri) a lot more low level control, thus making FlaskWebGui a lot more powerful for creating cross-OS desktop apps with Python and html, css, JS.

**Comment by ClimenteA** [comment]
Yes, I was looking into something similar. Tauri looks like in the future wants to implement support for python also.

**Comment by ClimenteA** [comment]
Taking discussion on https://github.com/ClimenteA/flaskwebgui/issues/89
