### ISSUE TITLE
`width=x`, `height=y` flags not respected

### ISSUE THREAD

**Issue by scipio-nl** [ClimenteA/flaskwebgui#86]
Hi Alin, you mentioned this yourself already in your documentation, but I just thought to post this as an issue on my end the `width=x`, `height=y` flags are not respected.

**Comment by ClimenteA** [comment]
Yep, subprocess flags seem to be flaky

**Comment by ClimenteA** [comment]
Taking discussion on https://github.com/ClimenteA/flaskwebgui/issues/89
