### ISSUE TITLE
Add flag `always_on_top`

### ISSUE THREAD

**Issue by scipio-nl** [ClimenteA/flaskwebgui#87]
Hi Alin,
please add in the possibility with `always_on_top` to keep the app window always on top of other app windows.

**Comment by ClimenteA** [comment]
Hi,

Chromium browsers are open using the flags documented here: `https://peter.sh/experiments/chromium-command-line-switches/`. Didn't found any `always_on_top` flag unfortunately.

Checkout [pywebview](https://pywebview.flowrl.com/) a lot of improvements were done since last time I checked.

**Comment by scipio-nl** [comment]
LOL, if you close this issue by referring me to PyWebview, that I had commented on in issue #85 myself 9we were both typing at the same time probably), does that mean you don't have any intent to improve FlaskWebGui?

**Comment by ClimenteA** [comment]
:)) probably we typed at the same time. 

It's not a matter of intent it's a matter of my availability (any PR's are welcome). Current approach of using chrome with subprocess and some flags has reached it's limitations. 

Another approach for more control needs to be implemented, maybe something with Rust/webview, I don't know.

**Comment by ClimenteA** [comment]
PyWebview is a good alternative. Try this:

```py

import webview
from threading import Thread

app = Flask()/FastApi()/Other()

@app.someRoute()
def view():
    return "X"
etc

if __name__ == "__main__":
   
    window = webview.create_window('Woah dude!', 'https://pywebview.flowrl.com')
    
    pywebview_thread = Thread(webview.start)
    pywebview_thread.start()
    app.run()
    pywebview_thread.join()
```

At the time of writting flaskwebgui pywebview had some issues with pyinstaller, at this point probably they are fixed (not sure).
If pywebview has what you need - go for it :)

**Comment by scipio-nl** [comment]
Implementing Tauri, is DEFINITELY the right approach in my mind. Also, consider the following:

- Tauri (which also spawns a client's native Webview but adds a lot more control) is originally targeted at writing packaged Desktop apps with html, css, JS on the frontend UI, and Rust at the backend
- Tauri does support (via SideCar, as mentioned) including Python binaries
- but doing so isn't currently the main objective of the Tauri team, so it seems; Tauri is currently NOT targeting Python solutions
- but for Python devs, to code Desktop Apps, the stack `html, css, JS` for the frontend and `Flask` for the backend, wrapped in a Tauri package, would be ideal.

In my mind "FlaskWebGui" could be that solution, and it shouldn't require complex configurations to get going, ideally.

**Comment by ClimenteA** [comment]
I agree, Tauri offers a lot of control. I'll look into it.

**Comment by scipio-nl** [comment]
I'm willing to help you with that. GitHub seems to have removed direct messaging, but if you want to talk to me directly about a collab, I'm on Discord. Would that work?

**Comment by scipio-nl** [comment]
PS, I had already (before you commented) gotten PyWebview to work just fine; one downside of that (at least that's what made me look into FlaskWebGui to begin with), is that I haven't been able to use something like the Chrome Developer Tools provide. But for now I'll just implement a flag option to either run my app with FlaskWebGui whilst developing and PyWebview when deploying.

Still, I'm interested to incorporate Tauri and utilize all three (add to that a cross-OS packager that always works) into one easy to use Python module that irons out any build workflow complexities.

**Comment by ClimenteA** [comment]
Thank you! That would be very helpful. I think we can keep the discussions here for now.

I was looking into Tauri here are my thoughts:

As a lazy dev what I don't like the installing rust part. They are using a webview package build in rust: [wry](https://github.com/tauri-apps/wry), but we can use [webview-python](https://github.com/zserge/webview-python) - it's a wrapper around a [C cross-platform webview](https://github.com/webview/webview). We can make a rust python wrapper of `wry` if we want to get fancy, but I think the C webview will suffice.

Now the hard part: 
How to integrate [webview-python](https://github.com/zserge/webview-python) with any python webframework and frontend framework with minimal config on dev side?

The higher level API:

```py

from flaskwebgui import FlaskUI
from main import start_app

FlaskUI(start_app, width=600, height=500, always_on_top=True, **extraFlags).run()

```

Function `start_app` should be a function which starts the webserver be it Flask/FastApi/Django doesn't matter. Followed by the window flags like width, height, window position,  always_on_top etc, but we should leave some room for some extra flags in kwargs (this way if webview is updated we don't need to add each time a parameter to match that update - can be done async).

What do you think?

**Comment by scipio-nl** [comment]
Yes I agree with that approach (your higher level API example).
Indeed the difference between having a C or Rust cross-platform WebView rendering library, would yield very little performance differences, when the main objectives are:

- to spawn a localhost-run Python backend to interface with an html / css / JS based frontend UI (message passing over http / AJAX), and
- to package/freeze and distribute the entire app with macOS, Windows and Linux as primary desktop targets.

Being dependent on PyInstaller or another Python packager shouldn't be the case even to be able to deploy as a desktop app, as that is the core objective to begin with! (That task is handled by Tauri itself too, when considering an html / css, js / Rust tech stack for a desktop app).

**Comment by ClimenteA** [comment]
I like the Tauri packager which creates an installer for each platform. In our case Pyinstaller along with a github action to generate a binary for each platform should be enough.

**Comment by scipio-nl** [comment]
And I also agree on the build process to be simple and user friendly without needing to configure a lot of stuff to freeze/package the app to the desired target.

**Comment by ClimenteA** [comment]
Taking discussion on https://github.com/ClimenteA/flaskwebgui/issues/89
