### ISSUE TITLE
Refactor and integrate webview-python into flaskwebgui

### ISSUE THREAD

**Issue by ClimenteA** [ClimenteA/flaskwebgui#89]
Currently there are some limitations using python subprocess package with chromium flags:
- sometimes flags are not taken into consideration (width, height), limited pool of flags;
- hard to determine when the window was closed - the current hacky way of pooling doesn't work if computer goes idle (app will close). If `close_server_on_exit` is set to False will prevent the previous issue, but will spawn multiple python processes in the background (these will be closed when pc is shutdown).

Refactor and integrate https://github.com/zserge/webview-python into flaskwebgui. Using webview-python should give us more control on the window.

Higher level api:
```py
from flaskwebgui import FlaskUI
from main import start_app

FlaskUI(start_app, width=600, height=500, always_on_top=True, **extraFlags).run()
```

- Function start_app should be a function which starts the webserver be it Flask/FastApi/Django doesn't matter. Followed by the window flags like width, height, window position, always_on_top etc, but we should leave some room for some extra flags in kwargs (this way if webview is updated we don't need to add each time a parameter to match that update - can be done async).
- `on_startup` - parameter which calls once the function provided on app startup;
- `on_shutdown` - parameter which calls once the function provided on app shutdown;

**Comment by ClimenteA** [comment]
@scipio-nl do you want to start?

**Comment by scipio-nl** [comment]
```python
FlaskUI(
    target=start_app, 
    width=600, 
    height=500, 
    min_size=(600, 500),   # optionally disallow resizing below certain viewport specs
    always_on_top=True,   # enable multi-screens
    debug=True                   # spawn Chrome for Developer Tools when coding/debugging, native Webview if `False`
    title=title,                       # set app window title
    **extraFlags).run()
```

**Comment by ClimenteA** [comment]
Added a few more:

```py
FlaskUI(
    target=start_app, 
    resizable=True,
    fullscreen=False,
    confirm_close=False, 
    width=600, 
    height=500, 
    min_size=(600, 500),   # optionally disallow resizing below certain viewport specs
    always_on_top=True,    # enable multi-screens
    debug=True             # spawn Chrome for Developer Tools when coding/debugging, native Webview if `False`
    title=title,           # set app window title
    **extraFlags).run()
```

**Comment by ClimenteA** [comment]
Unfortunately package `webview-python` didn't even install on my machine... 

But, I did this weekend a full refactor removing the need of that js keep alive script, let some room for extending FlaskUI class and overall more tidy code.

Added docs under `Limitations` section in which I specify that the control of the window is limited.
