### ISSUE TITLE
When starting flaskwebgui all chrome windows are closed

### ISSUE THREAD

**Issue by ClimenteA** [ClimenteA/flaskwebgui#9]
Each time a flaskwebgui instance runs all chrome instances are closed.

**Comment by KenSingson** [comment]
Hi Sir, following up on this since I have the same problem too. 

Thanks.

**Comment by ClimenteA** [comment]
Bellow version doesn't close all chrome instances when flaskwebgui starts but when flaskwebgui instance is closed it doesn't close the flask server..
`pip install flaskwebgui==0.1.2`

**Comment by trixal** [comment]
**Please fix the issue of launching the desktop app, but keep open Chrome closed?**
If people have collaborators with an open management browser, etc., you need to ensure the functionality of the app for people.
This is not how they will welcome an application that will drop their Chrome. And this is true even when the app points to Chromium, and the default is Google Chome. It doesn't change anything. I thought of a distribution solution with its chromium, but it has no effect.

**Comment by ClimenteA** [comment]
Made an update, the new version 0.1.7 it's closer to how it should behave.

**Comment by ClimenteA** [comment]
Deleted 0.1.7 version causes issues on windows..
