### ISSUE TITLE
How to close connections on browser window closing ?

### ISSUE THREAD

**Issue by vikramsamak** [ClimenteA/flaskwebgui#91]
This is my code to run GUI, but there is issue while closing connections … How to close connection on exit ?
I have set close_server_on_exit=False for not closing connection during testing a GUI.

In short, I want close connection whenever I close the browser window. How to do that ?

`from flaskwebgui import FlaskUI
from main import app

FlaskUI(app, start_server='flask', width=1280, height=720,
        close_server_on_exit=False, host="localhost", port=8000).run()
`

**Comment by ClimenteA** [comment]
close_server_on_exit=False - will not close the server 

close_server_on_exit=True (the default) - will close the server after a few seconds

Make sure to add the JavaScript code from the docs in your index.html file.

If you are using Django unfortunately server will not close.. but that will not affect how the app works.

When you package the app make sure to add the no console flag (pyinstaller/pyvan).

From the user perspective this will not get noticed.

**Comment by vikramsamak** [comment]
I'm using flask ... is there any way ?

**Comment by ClimenteA** [comment]
close_server_on_exit=True

**Comment by vikramsamak** [comment]
I used the same parameter but it did not close the connection when I closed the browser window.(edge)

**Comment by ClimenteA** [comment]
Try to add - start_server="flask" with close_server_on_exit=True.

The connection should close after 5 seconds

**Comment by vikramsamak** [comment]
I seen that sir.. but I wanna close the server whenever I close the browser.....

**Comment by ClimenteA** [comment]
When closing the GUI (pressing X) it will not close the connection right away. 

Currently that's not possible.
