### ISSUE TITLE
How to provide a certificate

### ISSUE THREAD

**Issue by vsakkas** [ClimenteA/flaskwebgui#92]
I want to be able to provide a certificate so that the connection uses HTTPS instead of plain. I know how to do this with `unicorn` and `fastapi` but I do not see any options for that on the `FlaskUI` object. Is this supported?

**Comment by ClimenteA** [comment]
FlaskUI is for desktop apps - you don't need https on local. 
What you most probably need is [code signing](https://www.digicert.com/signing/code-signing-certificates). Without code signing the user will receive a warning that the software may not be secure to run. See how you can do code signing with pyinstaller.

**Comment by vsakkas** [comment]
@ClimenteA Thanks for the quick response. Code signing is definitely a useful feature to have in desktop apps. However, the use case I am thinking is features such as WebRTC.
What I mean, is that if someone makes a desktop app with `flaskwebgui` that needs WebRTC with Javascript, then having an HTTP connection (even if it's on localhost) would not permit this feature to work. It is quite trivial to provide the certificate and key to something like FastAPI so I was wondering if that's something that could be supported.
If that's outside the scope of this project, it's understandable.

**Comment by ClimenteA** [comment]
Try to provide the security certificate if it works with just FastApi it should work with FlaskUI also (behind the scenes it uses 2 threads to make it work).

**Comment by vsakkas** [comment]
@ClimenteA Yes, that's what I am trying to do. However, in a usual FastAPI app, you provide the certificate to `uvicorn`, not the FastAPI object directly. Is there a way to do this here?

**Comment by ClimenteA** [comment]
The FlaskUI class has a param named `start_server` which receives a string or a function which starts the webserver. 

Try to modify this for your use case:

```
app = FastAPI()

def start_uvicorn():
    import uvicorn

    uvicorn.run(
        "main:create_app_factory",
        host="0.0.0.0",
        port=config.PORT,
        factory=True,
        reload=False,
        workers=2,
    )

if __name__ == "__main__":
    FlaskUI(start_server=start_uvicorn).run()
    
```
