### ISSUE TITLE
File Uploading failed by using post request.

### ISSUE THREAD

**Issue by vikramsamak** [ClimenteA/flaskwebgui#96]
I got this error 
flaskwebgui - [INFO] - 127.0.0.1 - - [07/Nov/2022 21:57:00] "POST /home HTTP/1.1" 400 

![image](https://user-images.githubusercontent.com/95061742/200364202-047ffe21-18c2-41d3-8379-d5355c884483.png)

Is there any solution ?

**Comment by vikramsamak** [comment]
In HTML template --
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <form action="/upload" method="post" enctype="multipart/form-data">
            <input type="file" name="file">
            <button type="submit">Upload</button>
        </form>
    </div>
</body>
</html>`
 in main.py
`from openpyxl import *
import pandas as pd
from openpyxl.styles.alignment import Alignment
from openpyxl.styles import Border, Side
from flask import Flask, jsonify, request
from flask import render_template, session
from flaskwebgui import FlaskUI  # import FlaskUI
import os




# Flask Code
app = Flask(__name__)
# app.secret_key = "login"
ui = FlaskUI(app, width=500, height=500)  # add app and parameters





@app.route("/", methods=['GET'])
def start():
    return render_template("input-test.html")

# upload route
@app.route("/upload", methods=['POST'])
def upload():
    if request.method == 'POST':
        f = request.form['file']
        f.save(f.filename)
        
    return render_template('input-test.html')




if __name__ == "__main__":
    app.run()  # for debug
    ui.run()
`

in gui.py:
`from flaskwebgui import FlaskUI
from main import app

FlaskUI(app, start_server='flask', width=1280, height=720,
        close_server_on_exit=False, host="localhost", port=8000).run()
`

**Comment by vikramsamak** [comment]
I'm still using the old version.

**Comment by vikramsamak** [comment]
I also tried after installing waitress but still it's not working.

**Comment by ClimenteA** [comment]
Does it work without flaskwebgui?

**Comment by ClimenteA** [comment]
In your first post you get a 400 not found : `/home HTTP/1.1" 400` - there is no `/home` endpoint.

**Comment by vikramsamak** [comment]
I corrected my code and posted again...

**Comment by vikramsamak** [comment]
> Does it work without flaskwebgui?

Yes it works with flask

**Comment by ClimenteA** [comment]
What is the error on upload?

**Comment by ClimenteA** [comment]
I tried your code it doesn't work with or without flaskwebgui.

You need `request.files['file']` instead of `request.form['file']` for it to work. Added an example in examples/flask-desktop you can take a look there.

**Comment by vikramsamak** [comment]
Thanks a lot for corrections 🙂

Vikram Samak

**Comment by ajmcgraw** [comment]
@ClimenteA since this is a local GUI, can I get the full path of the file instead of having to upload it to the server?

**Comment by ClimenteA** [comment]
You have access to the filesystem and you can do whatever you want where the flaskwebgui app is running.

**Comment by vikramsamak** [comment]
> @ClimenteA since this is a local GUI, can I get the full path of the file instead of having to upload it to the server?

You can access the full path of the file with the help of easygui module.

**Comment by ajmcgraw** [comment]
> You have access to the filesystem and you can do whatever you want where the flaskwebgui app is running.

I can access the whole file system but instead of file.tif, I would like to get the full path ie C:/user/documents/file.tif. Sometimes I am dealing with tifs that are 25gb and don't want to upload them

**Comment by ClimenteA** [comment]
Yep, just tell the user to add the file in C:/user/documents or whatever path - you can access it.

**Comment by vikramsamak** [comment]
Import easygui

    path = easygui.fileopenbox(title="window title", default="\*.tif")

**Comment by vikramsamak** [comment]
I used this in my current project

**Comment by vikramsamak** [comment]
I showed the short code above..you just have to use a path wherever u want...

**Comment by ajmcgraw** [comment]
```
@blueprint.route("/upload.html", methods=["GET", "POST"])
def files_upload():
    form = Files(request.form)
    requests = None
    
    if not current_user.is_authenticated:
        return redirect(url_for('authentication_blueprint.login'))
    
    user = Users.find_by_email(current_user.email)
    
    if form.is_submitted():
        requests = request.form
        path = easygui.fileopenbox(title="select file")
        full_path = os.path.abspath(path)        
            
    return render_template('home/upload.html', form=form,
                           ticket=user, requests=requests)
```

So here is my code, but it doesn't actually open the gui from flask.

**Comment by ajmcgraw** [comment]
nevermind, it works.
