### ISSUE TITLE
flaskwebgui not running with flask

### ISSUE THREAD

**Issue by tamajon** [ClimenteA/flaskwebgui#99]
Greetings, the problem is simple, the application closes right after starting, even with the configuration of the examples
[screen-capture.webm](https://user-images.githubusercontent.com/68070152/201662796-73aa9b4d-a860-4130-81d9-1a6e53df16a1.webm)

**Comment by ClimenteA** [comment]
I see you are using chromium - when it starts you can see and error `chrome path not found`. 
Please specify `browser_path=path/to/chromium/or/edge/browser` to `FlaskUI` class.

**Comment by tamajon** [comment]
Is there a way to use the default browser of the operating system?

**Comment by ClimenteA** [comment]
You see in the video it opens the url in the default browser, but I don't know why it doesn't load.

What is in the console after that?

**Comment by tamajon** [comment]
> You see in the video it opens the url in the default browser, but I don't know why it doesn't load.
> 
> What is in the console after that?

Exactly, that's why I thought it was a mistake. I'll check as soon as I get home.

**Comment by tamajon** [comment]
in fact, in the console there is no error message, it just closes the python script. It would be interesting to use webbrowser.open(url) to use the system's default browser, if it doesn't find chrome or edge. But I suppose it is something that you will analyze.

**Comment by ClimenteA** [comment]
Thanks, I'll check it out,

**Comment by ClimenteA** [comment]
thank you - added a fix in 1.0.3
